kind: pipeline
type: docker
name: default

steps:
  - name: clone-repo
    image: alpine/git
    commands:
      - git clone https://github.com/NarenPrakash/thymeleafExample.git
      - cp -r thymeleafExample/* .

  - name: build-java
    image: maven:3.8.6-openjdk-11
    commands:
      - mvn clean package -DskipTests

  - name: build-and-push-image
    image: plugins/docker
    settings:
      username: sowjanya135  # Your Docker Hub username
      password:
        from_secret: docker_password  # Secret for Docker Hub password
      repo: sowjanya135/drone-mvn  # Your Docker Hub repository name
      tags:
        - latest

  - name: deploy-app
    image: docker
    settings:
      auto_cleanup: true
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker pull sowjanya135/drone-mvn:latest  # Pull the image
      - docker run -itd -p 8080:8086 --name drone-docker sowjanya135/drone-mvn:latest  # Run the container after pulling the image

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
