kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3.8.4-openjdk-11
  commands:
  - mvn clean package

- name: publish
  image: plugins/docker
  settings:
    username: sowjanya135
    password: D0cker@135
    repo: sowjanya135/drone-mvn
    tags:
    - 1.0
  when:
    event:
      - push
      - tag

- name: deploy
  image: docker:dind
  privileged: true
  commands:
  - docker run -d -p 8080:8086 --name drone-docker sowjanya135/drone-mvn:1.0
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
