kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: docker:20.10.8  # Specify a specific Docker image version
  services:
  - docker:20.10.8  # Start Docker daemon service
  commands:
  - docker run -d -p 8080:8086 --name drone-docker sowjanya135/drone-mvn:1
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
