kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ubuntu
    commands:
      - apt update
      - apt install default-jdk maven -y
      - mvn test
      - mvn package

  - name: publish
    image: plugins/docker
    settings:
      username: sowjanya135
      password:
        from_secret: docker_password  # Use secrets for security
      repo: sowjanya135/drone-mvn
      tags:
        - 1.0

  - name: deploy
    image: docker:dind
    commands:
      - docker run -d -p 8080:8086 --name drone-docker sowjanya135/drone-mvn:1
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
