kind: pipeline
name: default

steps:
- name: deploy
  image: docker:20.10.8  # Use Docker to deploy the container
  commands:
  - docker run -d -p 8080:8086 --name drone-docker sowjanya135/drone-mvn:1  # Deploy your Docker image

- name: test
  image: docker:20.10.8  # Use Docker-in-Docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock  # Docker socket
  commands:
  - sleep 5  # Allow Docker to start
  - docker ps -a  # List Docker containers

services:
- name: docker
  image: docker:20.10.8  # Docker service
  privileged: true  # Necessary for DinD
  volumes:
  - name: dockersock
    path: /var/run/docker.sock  # Docker socket for the service

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock  # Host's Docker socket
