kind: pipeline
type: docker
name: default

steps:
  - name: deploy-app
    image: docker:20.10.7-dind  # Use the Docker-in-Docker image
    settings:
      auto_cleanup: true 
    commands:
      - dockerd &  # Start the Docker daemon in the background
      - sleep 5  # Wait for the Docker daemon to start
      - docker pull sowjanya135/drone-mvn:latest  # Pull the image
      - docker run -itd -p 8080:8086 --name drone-docker sowjanya135/drone-mvn:latest  # Run the container
