kind: pipeline
name: default

steps:
  - name: deploy-app
    image: docker:latest  # Use Docker to run the container
    privileged: true  # Necessary for Docker commands if using Docker-in-Docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock  # Mount the Docker socket for access
    commands:
      - docker ps -a  # List all containers (optional, for debugging)
      - docker run -d -p 8080:8080 --name java-app sowjanya135/drone-mvn:latest  # Deploy your Docker image

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock  # Correctly mount the Docker socket
