kind: pipeline
type: docker
name: default

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/NarenPrakash/thymeleafExample.git
      - cp -r thymeleafExample/* .

  - name: build
    image: maven:3.8.6-openjdk-11
    commands:
      - mvn clean package -DskipTests

  - name: build-docker-image
    image: docker
    commands:
      - echo "FROM openjdk:11-jre-slim" > Dockerfile
      - echo "COPY target/*.jar app.jar" >> Dockerfile
      - echo "ENTRYPOINT [\"java\", \"-jar\", \"app.jar\"]" >> Dockerfile
      - docker build -t sowjanya135/drone-mvn:1.0 .

  - name: publish
    image: plugins/docker
    settings:
      username: sowjanya135
      password:
        from_secret: docker_password  # Store your Docker password in Drone secrets
      repo: sowjanya135/drone-mvn
      tags:
        - 1.0

  - name: deploy
    image: docker:dind
    settings:
      privileged: true  # Required for running Docker in Docker
    commands:
      - docker run -d -p 8080:8080 --name java-app sowjanya135/drone-mvn:1.0

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock  # Required for Docker-in-Docker to work
