kind: pipeline
type: docker
name: default
trusted: true

steps:
  - name: clone-repo
    image: alpine/git
    commands:
      - git clone https://github.com/NarenPrakash/thymeleafExample.git
      - cp -r thymeleafExample/* .

  - name: build-java
    image: maven:3.8.6-openjdk-11
    commands:
      - mvn clean package -DskipTests

  - name: create-docker-image
    image: docker:latest
    privileged: true  # Add this line
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - echo "FROM openjdk:11-jre-slim" > Dockerfile
      - echo "COPY target/*.jar app.jar" >> Dockerfile
      - echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile
      - docker build -t sowjanya135/drone-mvn:1.0 .

  - name: publish-docker-image
    image: plugins/docker
    settings:
      username: sowjanya135
      password:
        from_secret: docker_password  # Ensure this secret is set in Drone
      repo: sowjanya135/drone-mvn
      tags:
        - 1.0

  - name: deploy-app
    image: docker:latest
    privileged: true  # Add this line
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker run -d -p 8080:8080 --name java-app sowjanya135/drone-mvn:1.0

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
