kind: pipeline
type: docker
name: default

steps:
  - name: clone-repo
    image: alpine/git
    commands:
      - git clone https://github.com/NarenPrakash/thymeleafExample.git
      - cp -r thymeleafExample/* .

  - name: build-java
    image: maven:3.8.6-openjdk-11
    commands:
      - mvn clean package -DskipTests

  - name: build-and-push-image
    image: plugins/docker
    settings:
      username: sowjanya135  # Your Docker Hub username
      password:
        from_secret: docker_password  # Ensure this secret is set in Drone
      repo: sowjanya135/drone-mvn  # Your Docker Hub repository name
      tags:
        - latest  # You can specify multiple tags if needed
      dockerfile: Dockerfile  # Specify the Dockerfile path if not in the root directory

  - name: deploy-app
    image: docker:latest
    privileged: true 
    commands:
      - docker run -d -p 8080:8080 --name java-app sowjanya135/drone-mvn:latest

volumes:
  # No volume mounts since we're not using privileged mode.
